import { toRuntime } from "fumadocs-mdx"
import * as docs_0 from "../content/docs/index.mdx?collection=docs&hash=d1b8eee0ccad9f002943f8b6e74a6519"
import * as docs_1 from "../content/docs/page1.mdx?collection=docs&hash=d1b8eee0ccad9f002943f8b6e74a6519"
import * as docs_2 from "../content/docs/page2.mdx?collection=docs&hash=d1b8eee0ccad9f002943f8b6e74a6519"
import * as docs_3 from "../content/docs/b_TimeToShine/folder_page1.mdx?collection=docs&hash=d1b8eee0ccad9f002943f8b6e74a6519"
import * as docs_4 from "../content/docs/b_TimeToShine/folder_page2.mdx?collection=docs&hash=d1b8eee0ccad9f002943f8b6e74a6519"
import * as meta_0 from "../content/docs/meta.json?collection=meta&hash=d1b8eee0ccad9f002943f8b6e74a6519"
import * as meta_1 from "../content/docs/b_TimeToShine/meta.json?collection=meta&hash=d1b8eee0ccad9f002943f8b6e74a6519"
export const docs = [toRuntime("doc", docs_0, {"path":"index.mdx","absolutePath":"C:/Users/grigo/OneDrive/Desktop/Webpage_Fin/swift-android-site/content/docs/index.mdx"}), toRuntime("doc", docs_1, {"path":"page1.mdx","absolutePath":"C:/Users/grigo/OneDrive/Desktop/Webpage_Fin/swift-android-site/content/docs/page1.mdx"}), toRuntime("doc", docs_2, {"path":"page2.mdx","absolutePath":"C:/Users/grigo/OneDrive/Desktop/Webpage_Fin/swift-android-site/content/docs/page2.mdx"}), toRuntime("doc", docs_3, {"path":"b_TimeToShine\\folder_page1.mdx","absolutePath":"C:/Users/grigo/OneDrive/Desktop/Webpage_Fin/swift-android-site/content/docs/b_TimeToShine/folder_page1.mdx"}), toRuntime("doc", docs_4, {"path":"b_TimeToShine\\folder_page2.mdx","absolutePath":"C:/Users/grigo/OneDrive/Desktop/Webpage_Fin/swift-android-site/content/docs/b_TimeToShine/folder_page2.mdx"})];
export const meta = [toRuntime("meta", meta_0, {"path":"meta.json","absolutePath":"C:/Users/grigo/OneDrive/Desktop/Webpage_Fin/swift-android-site/content/docs/meta.json"}), toRuntime("meta", meta_1, {"path":"b_TimeToShine\\meta.json","absolutePath":"C:/Users/grigo/OneDrive/Desktop/Webpage_Fin/swift-android-site/content/docs/b_TimeToShine/meta.json"})];